# Uncomment this line to define a global platform for your project
platform :ios
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HQAClient' do
pod 'PLCrashReporter', '~> 1.2'
end

